name: Marca entrada GeoVictoria

on:
  # Ejecutar manualmente desde GitHub UI
  workflow_dispatch:

  schedule:
    - cron: '30 18 * * 4' # Lunes a viernes a las 8:00 CLT = 12:00 UTC

jobs:
  test-login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Chromium and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Geovictoria bot
      env:
        GEO_EMAIL: ${{ secrets.GEO_EMAIL }}
        GEO_PASS: ${{ secrets.GEO_PASS }}
      run: python marca_entrada.py
